### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#370]
## Proposal

* Every x seconds an "analysis tick" is performed
* The following metrics are collected for each such tick:
    * For each viewport and for the whole exercise:
        * Number of patients per triage category
        * Number of patients currently cared for (Optional)
        * Number of personnel per type (Optional)
        * Number of vehicles per type
        * Number of clients in the viewport/exercise
    * Number of vehicles in transfer (transporting patient, not transporting a patient) (Optional)
    * Number of personnel (without vehicle) in transfer
* These metrics can be seen by trainers, in an additional ExerciseAnalysisModal 
     * Visualisation via diagrams
     * Dropdown for choosing the viewport/the whole exercise
* Optional: the current values for a viewport are shown in the viewport-popup

![image](https://user-images.githubusercontent.com/18506183/167396796-147f3615-e9e7-4f64-9e67-b6e48df8453c.png)

## Problems

* What should happen if a viewport gets deleted/renamed during the exercise? (Same problem as #336 ?)

**Comment by Dassderdie** [comment]
@christianzoellner Can you think of any additional metrics that should be collected during the exercise? All the hospital metrics will be added later.

**Comment by christianzoellner** [comment]
One question first @Dassderdie : Do the merics actually have to be collected every X seconds?

 Alternatively, couldn't we just compute the numbers on demand when they should be displayed? Or could we add some code to the "move action" reducer that checks wether the movement changes the viewport assignment?

For the actual statistics = diagrams in the end, we could "reply" the exercise and use the reducer again to determine which action constitute a + or - for the statistics.

**Comment by Dassderdie** [comment]
> One question first @Dassderdie : Do the merics actually have to be collected every X seconds?
> 
> Alternatively, couldn't we just compute the numbers on demand when they should be displayed? Or could we add some code to the "move action" reducer that checks wether the movement changes the viewport assignment?
> 
> For the actual statistics = diagrams in the end, we could "reply" the exercise and use the reducer again to determine which action constitute a + or - for the statistics.

I think this is currently the best solution.

> “The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; premature optimization is the root of all evil (or at least most of it) in programming.”
> 
> Donald Knuth

If we realize later that this is indeed a performance problem, we can optimize it later.

**Comment by christianzoellner** [comment]
> I think my proposal is currently the best solution.

You always think that. :-)
Even tough you are offen correct, let's discuss it a bit more. Maybe in person instead of via text.

> If we realize later that this is indeed a performance problem, we can optimize it later.

I'm not sure if it's only about performance. Some parts of your solution seem to me to be not the most simple option.

**Comment by Dassderdie** [comment]
> > I think my proposal is currently the best solution.
> 
> You always think that. :-) 

Obviously ;)

> Even tough you are offen correct, let's discuss it a bit more. Maybe in person instead of via text.

Agreed.

**Comment by christianzoellner** [comment]
> @christianzoellner Can you think of any additional metrics that should be collected during the exercise? All the hospital metrics will be added later.

I think you covered the important points.

Let me present my (prioritized) wishlist for you so that you can compare it against your own notes comparison:

## Visualizations

### (a) Show the current numbers of patients (by category) and resources (by type) for each viewport in trainer view  during a live exercise and during playback.
- [ ] (must-have) When a trainer clicks on an viewport, they see  the numbers in a popup. Alternatively, the numbers are always shown in a box in the corner.
- [ ] (should-have) Make this information available as a zoom-out feature for the trainer view. When a trainer zooms out, they automatically see only viewport boxes with some info text in them (text scale might depend on viewport size to allow hierarchical structures) instead of individual icons.
- [ ] (nice-to-have) Additionally, a number of required resources capacities would be useful, so that a trainer can easily take over the communication for a  number of regions. 
- [ ] (nice-to-have) It might also be useful to highlight recently changed numbers for a certain timem Might be in different colors, e.g. green (added personnel, patients moved away), red (added patients, reduced personell), other (died patients).

### (b) Show diagrams/curves for the number of patients (by category) and vehicles/personnel (by type) in a certain area.
- [ ] (must-have) Trainers can select scope and metric of the diagram (see below)
- [ ] (must-have) A chart is shown with either a continuous curve or series of bars for one metric. 
- [ ] (should-have) The cure or bars are stacked with the different component.
- [ ] (should-have) The numbers of patients or resources are shown in a table with one column for each X minutes (X might depend on overall exercise duration, so that there are always Y columns).
- [ ] (should-have) In the visualization, for one scope, there always is one diagram for a patient metric and one for a resources metric, where for both chart the specific metric can be selected.
- [ ] (nice-to-have) Show statistics for two scopes side-by-side to allow didactic comparisons (e.g. "many patients here, many resources there, why did you not distribute?").



## Metrics

### (a) Patients

- [ ] (must-have) Total number of patients only
- [ ] (must-have) Number of vpatients categorized per color (stacked chart)
- [ ] (nice-to-have) Numbers for one patient color (might be used to to highlight a specific aspect)


### (b) Resources

- [ ] (must-have) Total number of vehicles
- [ ] (must-have) Number of vehicles categorized per type (stacked chart)
- [ ] (nice-to-have) Numbers for one vehicle type (might be used to to highlight a specific aspect)
- [ ] (should-have) Number of disembarked personnel
    - In most cases personnel == vehicles, and it is easier to count the vehicles. However, it might be valuable to show disembarked personnel because they are the ones who are available to treat patients. Especially for areas which can only be reached on foot it is important to have this metric.
- [ ] (nice-to-have) Number of embarked personnel (i.e. persons that are not utilized for treatment, this might be a very specific fault you want to present to trainees in some situations).
- [ ] (should-have) Number of doctors (probably the only qualification level that is really interesting and not being managed automatically).
- [ ] (nice-to-have) Number of personnel by .
- [ ] (nice-to-have) Number of parked vehicles (i.e. with disembarked personnel).
- [ ] (nice-to-have) Number of vehicles with their personal onboard = that are ready to be deployed.

### (c) Other

- [ ] (should-have) Overall exercise: Number of started patient transports to hospitals (if you implement a hospital transport system as discussed during some of the interviews)



## Diagrams scopes

- [ ] (must-have) Scope can be any specific viewport.
- [ ] (must-have) Scope can be the whole exercise.
- [ ] (should-have) Scope can be the "anything that is in a viewport", in order to exclude vehicles etc that trainer might have prepared waiting "outside" viewports for spontaneous insertion.
- [ ] (nice-to-have) Scope can be .

**Comment by Dassderdie** [comment]
All further improvements are tracked in #385
