### ISSUE TITLE
Slow import of exercises

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#461]
It can take a very long time to import an exercise. It should be checked whether any improvements in loading time without losing validation can be made.

**Comment by Dassderdie** [comment]
Instead of applying all actions in a separate immer.js context, they could all be applied in one. This would use the same performance improvement I used in the version history. It is only relevant whether all actions together are correct, therefore the sandboxing via the immer proxy is not necessary.

**Comment by Dassderdie** [comment]
> Instead of applying all actions in a separate immer.js context, they could all be applied in one. This would use the same performance improvement I used in the version history. It is only relevant whether all actions together are correct, therefore the sandboxing via the immer proxy is not necessary.

Or even completely without immer.js by cloning the initial state and mutating it directly.
