### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#594]
At the moment, this repo has no license specified. When working on and extending this project, we'd like to have a license in order to be able to add dependencies and respect their respective licenses.

@Dassderdie @ClFeSc @anonym-HPI @hpistudent72 since the code in this repo is mainly your work it seems like you should decide which license to use. Christian told us that you have discussed this already, but the issue might be private, so we did not find anything on this topic.

**Comment by Dassderdie** [comment]
The issue is private. I wrote the new team a brief summary of the internal discussion as I don't know whether the everyone else wants this public.

@anonym-HPI @ClFeSc @hpistudent72 
Feel free to comment a summary of your thoughts here.

My opinion:
* The licence **must** state that everyone is allowed to read the source code.
* I take no liability for the correctness etc. of the code
* It **should** be as permissive as possible to not hinder development on this project. But I would also agree to any more restrictive license.

**Comment by ClFeSc** [comment]
> My opinion:
> 
>   * The licence **must** state that everyone is allowed to read the source code.
> 
>   * I take no liability for the correctness etc. of the code
> 
>   * It **should** be as permissive as possible to not hinder development on this project. But I would also agree to any more restrictive license.

I agree entirely with @Dassderdie on this issue.

**Comment by anonym-HPI** [comment]
I supported the idea of AGPL v3 (or so is it called).
Nextcloud for example has this license.
The reason for the "A" as this software is not compiled and installed (but distributed through a webserver).
Meaning GPL alone would allow one to change/improve the code and even sell it as a service without contributing back to this project.
This what I would like to hinder.

Any company should be allowed to use it and even make money of it, but change/improvements should be there for all.
What I would exclude (and is already happening for images) are images from the license, as well as privately generated templates or scenarios. These any could create and keep private. As long as they e.g. don't create a new template editor or improve what can be templated, imported or exported.

That is my stance on this.

I know there is the risk that companies don't want to improve it, but if they could without giving back this project could die.

I would therefore make it possible for companies to take this code, put their own branding on it, release scenarios and get money via training courses or so.
This way there are people that can like pay a person to train them, but the project is still available for the ones with all features, that don't have a lot of money and want to train for little cost in their town or so.

Of course the risk is that the project will not be developed any further. 
The risk without such a license is that the project dies, because a company copies it and improves it. That would result in a closed source software while this company would not have much of competition
I am no market expert, but I would rather have this project not be developed a lot and maybe help a few people (and of the project is at a minimum level of features, it should not necessarily be that important to get many updates frequently), than being eaten by a company.

**Comment by lukasrad02** [comment]
In general, I prefer permissive over restrictive licenses. But in this case, I can understand why we'd rather use a restrictive license.

As far as I know (but we should definitely double-check before we decide finally), the AGPL includes the things you'd like to have, so

- everybody is allowed to read
- there is no warranty for the software and/or any of its features
- we're not liable for any consequences of using the software
- users have full permissions and copyright on any work created by using this software (i.e., running the application and creating an export, not "using" the source code to copy it into another project's source code)

Am I missing anything (besides being more permissive) you'd like to have?

What I'm not sure about is whether there are other copyleft licenses that are incompatible to the AGPL and might restrict which external libraries we can use. For what I know, (A)GPL is not that commonly used for JS applications, so we should make sure that choosing AGPL does not restrict our own possibilities during development too much.

**Comment by anonym-HPI** [comment]
> In general, I prefer permissive over restrictive licenses. But in this case, I can understand why we'd rather use a restrictive license.
> 
> As far as I know (but we should definitely double-check before we decide finally), the AGPL includes the things you'd like to have, so
> 
> - everybody is allowed to read
> - there is no warranty for the software and/or any of its features
> - we're not liable for any consequences of using the software
> - users have full permissions and copyright on any work created by using this software (i.e., running the application and creating an export, not "using" the source code to copy it into another project's source code)
> 
> Am I missing anything (besides being more permissive) you'd like to have?
> 
> What I'm not sure about is whether there are other copyleft licenses that are incompatible to the AGPL and might restrict which external libraries we can use. For what I know, (A)GPL is not that commonly used for JS applications, so we should make sure that choosing AGPL does not restrict our own possibilities during development too much.

With exporting, templates, images and such, you mean we don't have to alter/add smth to the license? Users are allowed to keep them under a different license (even no license)?

About restrictions of libraries I don't know.
The question is: Is there a license that when used code in another software (e.g. as library) forces this software to have an equal open license? Any license that allows proprietary should probably be fine?!
MIT for example lets you do what you want, so should be fine. Apache seems to be also fine.
Mozilla, same for GPL v3, LGPL v3 and of course AGPL v3.
Licenses under https://choosealicense.com/licenses/

Our work probably falls under what is described as "larger work" in the license descriptions on this website.

I am open for a private discussion, we could make a meeting next week, e.g. wednesday (in person or online), for all that want to particapate. Especially @Dassderdie @ClFeSc @hpistudent72 as we four have done most of the software. Of course you of the new project have agree about what license we choose, to not remove your work and as you want to improve the software, you would probably like a license that you want to work in the future.

**Comment by anonym-HPI** [comment]
This is the PR for AGPL v3.0 https://github.com/hpi-sam/digital-fuesim-manv/pull/636

**Comment by anonym-HPI** [comment]
https://github.com/hpi-sam/digital-fuesim-manv-public-test-scenarios/ has no mention of the license, we may put some mention there or so, so people can use at least the test scenarios.
@christianzoellner what do you think?
Corresponding issue is created [there](https://github.com/hpi-sam/digital-fuesim-manv-public-test-scenarios/issues/13), but I would say we discuss this, in this issue.

**Comment by anonym-HPI** [comment]
> > @christianzoellner what do you think?
> 
> I propose we just copy the AGPL license file into the public-test-scenarios repo. Should work here even without the readme and details.

We can do that, as long as there are only for testing (you mean just LICENSE.md and not LICENSE-README.md?)
Before we should ask all that contributed to these tests, if they are ok with that.

**Comment by lukasrad02** [comment]
As the test scenarios are rather data than code, I don't think it makes sense to use some source code license for that repo and would prefer a Creative Commons license.

Taking into consideration that most of the scenarios are really small and simple

> one-action are tests that test one action with very little overhead  
> *(from the README. "tests" refers to "scenarios", not to test case code)*

I would prefer a license that is as permissive as possible, i.e. (in order of preference):

1. CC0
2. CC BY 4.0

**Comment by christianzoellner** [comment]
works for me, i'm fine with either of your proposals @lukasrad02

**Comment by anonym-HPI** [comment]
> As the test scenarios are rather data than code, I don't think it makes sense to use some source code license for that repo and would prefer a Creative Commons license.
> 
> Taking into consideration that most of the scenarios are really small and simple
> 
> > one-action are tests that test one action with very little overhead  
> > *(from the README. "tests" refers to "scenarios", not to test case code)*
> 
> I would prefer a license that is as permissive as possible, i.e. (in order of preference):
> 
> 1. CC0
> 2. CC BY 4.0

I am ok with both. And source code license could be not the right choice.
If you would like, would you do a PR in this repo and maybe ask the others? You four seems to have contributed, but I am not sure if you copied from others and they also have to agree.

**Comment by anonym-HPI** [comment]
I have published a pull request for CC0 1.0 Universal https://github.com/hpi-sam/digital-fuesim-manv-public-test-scenarios/pull/14
You can give feedback or accept it after you read the message in the pull request.
