### ISSUE TITLE
Update mail address for feedback

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#653]

**Comment by christianzoellner** [comment]
Just to checkin: As far as I understand it, the imprint + privacy statement + other meta-content is not supposed to be part of the code/repo but should be provided externally during deployment.
Could be also do something like that for the feedback email? Then, other people might have different feedback channels for their deployments.

**Comment by Dassderdie** [comment]
> Just to checkin: As far as I understand it, the imprint + privacy statement + other meta-content is not supposed to be part of the code/repo but should be provided externally during deployment. Could be also do something like that for the feedback email? Then, other people might have different feedback channels for their deployments.

One could implement this via different [environments](https://angular.io/guide/build#configuring-application-environments). This would mean that one would have to customize this variable in the `environment.deployment.ts` (maybe via the `.example` approach) when building the deployment. This would also mean that one would have to rebuild it every time one changes it.
Alternatively, one could load it via JSON at runtime or simply embed the pages via an iframe/`innerHTML`...

**Comment by anonym-HPI** [comment]
I would propose to have it also be setable as and `ENV` variable in `.env` (`.env.example`) for docker deployments. An example is how the upload size was implemented (`DFM_UPLOAD_LIMIT`).

**Comment by lukasrad02** [comment]
> Could be also do something like that for the feedback email? Then, other people might have different feedback channels for their deployments.

Different *channels* would be rather difficult since we'd like to include the current version number in the mail subject. Therefore, we would have to build some kind of templating logic that would allow using a placeholder for the version number like so that other people could use "normal" weblinks without having them end with `?subject=Feedback zur Digitalen FüSim MANV Version X.Y.Z`. Just using other mail addresses (while keeping the subject as defined in our code) would be way more simple.

But in general, I think that people will either host this software as-is (in which case it would make sense to keep our mail address) or if they will apply changes to the code (in which case changing the mail address would make sense) its okay if changing the feedback channel would require some more effort than just setting an environment variable.

Therefore, I'd simply stick to the hardcoded approach. If you say it should be definitely customizable without changing the code, I would only support changing the mail address (but not changing the subjects or using other URLs) via environment variables, since introducing another `.example` file next to the `.env`/`.env.example` for the Angular environments seems to be overkill for me.

**Comment by christianzoellner** [comment]
Good point. Maybe hardcoding is sufficient.

Escpecially since it is temporary anyway. 
Once your project is about to finish, you will probably want to change this to a githug-issue-create-link or something similar or find another configurable solution. And any other hosters will not be active developers in the meantime.
