### ISSUE TITLE
Bug: In Participant Mode when dragging a vehicle to Simulated Region, a Wrong pop-up occurs

### ISSUE THREAD

**Issue by benn02** [hpi-sam/digital-fuesim-manv#683]
When I am In participant Mode and restricted to a viewport, when I put a vehicle into a simulated Region in that Viewport I get a false notification that the vehicle just arrived.

**Comment by Dassderdie** [comment]
I believe the underlying problem is rather that a move-action is send even if the element shouldn't be moved, but instead dropped on another element.

This would mean the current PR is fixing a symptom and not the underlying cause.

One could also fix this by refactoring the setState and applyAction ngrx-reducers into one ngrx reducer.

**Comment by benn02** [comment]
I do believe, that sending 2 separate Actions is correct here since the expected behaviour if a vehicle cant be added to a simulated region because there is personnel not in it is not that it teleports back. So both actions have to be processed separately.
