### ISSUE TITLE
Customer Feature Request: Add hover Text on Icons in Patient Description / Category 

### ISSUE THREAD

**Issue by christianzoellner** [hpi-sam/digital-fuesim-manv#818]
The patient description / category consists of series of 3 icons in different colors.
While this helps to create some sort of structure, the icons are not perfectly intitive. A hover / onmouseover text would help.

The mapping is as follows:
- "A" = gleichbleibend/stabil =  ➡ 
- "B" =  Lebensrettende Maßnahme erforderlich = 💔 
- "C" = Transportpriorität = ❗ 
- "D" = Komplikation = ⚠

**Comment by christianzoellner** [comment]
While we are at it, maybe the icon for D should be changes so that it is easier to distinguish from C?

**Comment by lukasrad02** [comment]
> While we are at it, maybe the icon for D should be changes so that it is easier to distinguish from C?

Do you have suggestions for the icons? At the moment, we're using bootstrap icons, so every icon listed at <https://icons.getbootstrap.com/> would be available without additional effort.

I don't really know what "Komplikation" means in a medical point of view and in what way it differs from ""Maßnahme erforderlich", so I do not have a suggestion for an alternative icon for `D`. But we could also change the icon for `C`, for example one of

- <https://icons.getbootstrap.com/icons/car-front-fill/> (Car)
  ![image](https://user-images.githubusercontent.com/49586507/228212020-3356b978-aa84-4be7-9594-2c47969836c9.png)
- <https://icons.getbootstrap.com/icons/truck/> (Truck)
  ![image](https://user-images.githubusercontent.com/49586507/228212077-52faa4c6-86ab-490b-bc2c-f89b7de415ff.png)
- <https://icons.getbootstrap.com/icons/hospital-fill/> (Hospital)
  ![image](https://user-images.githubusercontent.com/49586507/228211929-fe66ff35-3ced-420b-9947-57f41ae88157.png)
- <https://icons.getbootstrap.com/icons/signpost-fill/> (Road sign)
  ![image](https://user-images.githubusercontent.com/49586507/228211850-a4399856-cdbd-41d8-bf00-8c9792f123f9.png)

which would put emphasis on "Transport" (transport) instead of "Priorität" (priority), which would keep the exclamation mark available for "Komplikation"/`D`
